(lang dune 3.20)

(name micro_build)
(using menhir 2.1)

(generate_opam_files true)

(source
 (github christopherfujino/micro.build))

(authors "Christopher Fujino <author@example.com>")

(maintainers "Christopher Fujino <author@example.com>")

(license "BSD-3-Clause")

(documentation https://github.com/christopherfujino/micro.build)

(package
 (name micro_build)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends
   (ocaml (and (>= 5.4.0) (< 5.5.0)))
   (base (and (>= 0.17.3) (< 0.18.0)))
   dune
   )
 (tags
  ("build system")))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
